#!/usr/bin/env python3
"""Reproduce the experiment: run pipeline, generate report/figures, update README.

Usage:
    python scripts/reproduce.py            # full run (configs/full.yaml)
    python scripts/reproduce.py --smoke    # smoke test (configs/smoke.yaml)
    python scripts/reproduce.py --config <path>  # custom config
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Add src to path
_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
sys.path.insert(0, str(_PROJECT_ROOT / "src"))

from bike_demand_forecast.config import load_config  # noqa: E402
from bike_demand_forecast.pipeline import run_experiment  # noqa: E402
from bike_demand_forecast.reporting import generate_figures, generate_report  # noqa: E402


def _update_readme_from_summary(summary_path: str) -> None:
    """Replace the results block in README.md with current summary values."""
    readme_path = _PROJECT_ROOT / "README.md"
    summary_p = Path(summary_path)

    if not summary_p.exists():
        return

    with open(summary_p) as f:
        summary = json.load(f)

    methods = summary.get("methods", {})
    comparisons = summary.get("comparisons", {})
    selected = summary.get("selected_method", "unknown")

    lines = [
        "## Key Results",
        "",
        "*Results are autogenerated from the last experiment run.*",
        "",
        f"**Data source:** {summary.get('source', 'N/A')}  ",
        f"**Selected method:** {selected} (by calibration MASE)  ",
        f"**Test samples:** {summary.get('n_test', 0)}  ",
        "",
        "| Metric | seasonal_naive | ridge | random_forest | hist_gradient_boosting |",
        "|---|---|---|---|---|",
    ]

    for metric in ("mase", "mae", "rmse", "smape"):
        parts = [f"**{metric.upper()}**"]
        for m in ("seasonal_naive", "ridge", "random_forest", "hist_gradient_boosting"):
            v = methods.get(m, {}).get(metric)
            if v is not None:
                parts.append(f"{v:.4f}")
            else:
                parts.append("N/A")
        lines.append("| " + " | ".join(parts) + " |")

    lines.extend(
        [
            "",
            "### Prediction Intervals (90% target coverage)",
            "",
            "| Metric | seasonal_naive | ridge | random_forest | hist_gradient_boosting |",
            "|---|---|---|---|---|",
        ]
    )
    for metric in ("interval_coverage", "mean_interval_width", "winkler_score"):
        label = metric.replace("_", " ").title()
        parts = [f"**{label}**"]
        for method in ("seasonal_naive", "ridge", "random_forest", "hist_gradient_boosting"):
            value = methods.get(method, {}).get(metric)
            if value is None:
                parts.append("N/A")
            elif metric == "interval_coverage":
                parts.append(f"{value:.1%}")
            else:
                parts.append(f"{value:.2f}")
        lines.append("| " + " | ".join(parts) + " |")

    below_target = [
        method for method, values in methods.items() if values.get("interval_coverage", 0.0) < 0.9
    ]
    if below_target:
        lines.extend(
            [
                "",
                "**Coverage caveat:** The following methods fell below the 90% empirical "
                f"coverage target: {', '.join(below_target)}. Chronological calibration and "
                "test residuals are not guaranteed to be exchangeable; treat these intervals "
                "as experimental uncertainty estimates, not coverage guarantees.",
            ]
        )

    lines.append("")
    lines.append("### Paired MASE Improvement vs Seasonal Naive (95% bootstrap CI)")
    lines.append("")
    lines.append("| Method | Mean improvement | 95% CI | Probability of improvement |")
    lines.append("|---|---|---|---|")
    for method in ("ridge", "random_forest", "hist_gradient_boosting"):
        c = comparisons.get(method)
        if c and c.get("ci_lower") is not None:
            bp = c.get("bootstrap_probability_improvement", 0)
            lines.append(
                f"| {method} | {c['improvement_mean']:.4f} | "
                f"[{c['ci_lower']:.4f}, {c['ci_upper']:.4f}] | "
                f"{bp:.1%} |"
            )
        else:
            lines.append(f"| {method} | N/A | N/A | N/A |")

    lines.append("")

    new_block = "\n".join(lines)

    marker_start = "<!-- RESULTS:START -->"
    marker_end = "<!-- RESULTS:END -->"

    if not readme_path.exists():
        return

    content = readme_path.read_text()
    if marker_start in content and marker_end in content:
        before = content.split(marker_start, 1)[0]
        after = content.split(marker_end, 1)[1]
        new_content = before + marker_start + "\n" + new_block + "\n" + marker_end + after
        readme_path.write_text(new_content)


def main() -> int:
    parser = argparse.ArgumentParser(description="Reproduce bike demand forecasting experiment.")
    parser.add_argument("--smoke", action="store_true", help="Run smoke test.")
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help="Path to YAML config file (default: configs/full.yaml or configs/smoke.yaml).",
    )
    args = parser.parse_args()

    mode = "smoke" if args.smoke else "full"

    if args.config is None:
        config_path = str(_PROJECT_ROOT / "configs" / f"{mode}.yaml")
    else:
        config_path = args.config

    print(f"Bike Demand Forecasting -- {mode.upper()} run")
    print(f"  Config: {config_path}")

    try:
        cfg = load_config(config_path)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"Config error: {e}", file=sys.stderr)
        return 1

    results = run_experiment(
        cfg,
        output_dir="reports",
        mode=mode,
        config_path=config_path,
    )

    # Generate report and figures AFTER pipeline completes successfully
    base_dir = Path("reports")
    out_dir = base_dir / "smoke" if mode == "smoke" else base_dir
    metrics_dir = out_dir / "metrics"
    figures_dir = out_dir / "figures"
    tables_dir = out_dir / "tables"
    for d in [metrics_dir, figures_dir, tables_dir]:
        d.mkdir(parents=True, exist_ok=True)

    generate_report(results, out_dir)
    generate_figures(results, figures_dir)

    print(f"  Status: {results.metadata.status}")
    print(
        f"  Train/Cal/Test: {results.metadata.n_train}/{results.metadata.n_cal}/{results.metadata.n_test}"
    )
    print(f"  Selected method: {results.selected_method} (by calibration MASE)")
    for method in ("seasonal_naive", "ridge", "random_forest", "hist_gradient_boosting"):
        m = results.method_metrics[method]
        print(f"    {method}: MASE={m['mase']:.4f}, MAE={m['mae']:.2f}")

    # Update README only for full run and after all artifacts are written
    if mode == "full":
        summary_path = base_dir / "metrics" / "summary.json"
        _update_readme_from_summary(str(summary_path))
        print("  README results block updated.")

    print("  Artifacts: reports/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
